# Generated by Django 3.1.7 on 2021-02-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210222_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default='erik', max_length=32, null=True),
        ),
    ]
